### ISSUE TITLE
Supervisors cannot approve time off requests

### ISSUE THREAD

**Issue by austinspooner** [BEMADEV/HR-Management#10]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When a supervisor clicks on the email link to approve a time off request they get the following error message: 
<img width="638" alt="image" src="https://github.com/BEMADEV/HR-Management/assets/657005/c173d34b-53ed-42a6-9d59-764ba62337e6">

### Expected Behavior

Expected Behavior

They would get this screen:
<img width="1250" alt="image" src="https://github.com/BEMADEV/HR-Management/assets/657005/706e9a16-5461-47f9-b6ac-85f60458a1a8">

### Actual Behavior

Actual Behavior

<img width="638" alt="image" src="https://github.com/BEMADEV/HR-Management/assets/657005/c173d34b-53ed-42a6-9d59-764ba62337e6">

### Steps to Reproduce

Using Rock version 15 or 15.1 create a PTO request and have the supervisor be a Rock user that is not an administrator. They will then get the Not Authorized error

### Rock Version

15.1

### Plugin Version

latest

### Client Culture Setting

en-us

**Comment by tcavaletto** [comment]
@austinspooner What are your HasReviewRights and HasViewRights attribute values returning for that workflow? The lava for both should be returning _True_.

**Comment by tcavaletto** [comment]
Unable to Reproduce
