### ISSUE TITLE
PTO tab appears on all screens, including donors, churches, etc

### ISSUE THREAD

**Issue by alwaysbetterthaniderserve** [BEMADEV/HR-Management#11]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

the PTO tab appears on every person and org (including churches), even if they aren't an employee. 

### Expected Behavior

The PTO tab should only appear on employees

### Actual Behavior

The PTO tab appears on every org and person and donor in the database

### Steps to Reproduce

-Look up any person in rock
-top menu bar has PTO for their profile

### Rock Version

16.0

### Plugin Version

1.1.6.14 

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment]
This is present on all profiles as the default for a child page of the Person Profile page so that new profiles can be marked as staff, similar to how the contributions tab still exists for profiles who have not given.
