### ISSUE TITLE
Manual allocation of hours causes Rock to just spin

### ISSUE THREAD

**Issue by robblehead** [BEMADEV/HR-Management#13]
### Please go through all the tasks below

- [x] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When attempting to edit an allocation on a specific person's profile, Rock just has the spinning icon.

### Expected Behavior

Allow editing the profile

### Actual Behavior

Rock loading icon just spins

### Steps to Reproduce

Click on HR tab of persons profile, click the allocation, click edit

### Rock Version

v16.4

### Plugin Version

1.1.17.14

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment]
- This was due to the comment section having HTML added from a custom workflow.
